### ISSUE TITLE
Chords without text are set down vertically

### ISSUE THREAD

**Issue by Taxel** [cgnieder/leadsheets#16]
Hi,

I have a problem which is easily illustrated in the following picture:

![image](https://i.imgur.com/IPWsvKu.png)

As you can see, the chords slide down vertically when there is enough space in the line below.
How can I prevent this?

My code is quite normal:

```latex
\begin{chorus}
	%refrain

	^{C} I'm here without you baby, ^{G} But you're still on my lonely ^{Am}mind  

	I think about you baby ^{F}and  I dream a^{G}bout  you all the  ^{C}time 

	I'm here without you baby, ^{G}  But you're still with me in my ^{Am}dreams ,
                            
	And to^{F}night , there's  ^{G}only  you and ^{C}me   ^{G}yeah .  ^{Am}  ^{F}  ^{G} 
\end{chorus}
```

Thanks in advance, love the project.
Taxel

**Comment by cgnieder** [comment]
I get the following from your code:

```latex
\documentclass{article}

\usepackage{leadsheets}
\begin{document}

\begin{song}{}
\begin{chorus}
  ^{C} I'm here without you baby, ^{G} But you're still on my lonely ^{Am}mind

  I think about you baby ^{F}and I dream a^{G}bout you all the ^{C}time

  I'm here without you baby, ^{G} But you're still with me in my ^{Am}dreams ,
                        
  And to^{F}night , there's ^{G}only you and ^{C}me ^{G}yeah .  ^{Am} ^{F} ^{G}
\end{chorus}
\end{song}

\end{document}
```

![grafik](https://user-images.githubusercontent.com/2248538/66048064-33622280-e529-11e9-823f-762d6fb734b2.png)

which means you are doing something which you are not telling but which is crucial in order to answer your question. This is a perfect example why *every* helper *always* asks for a complete minimal example.
